/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views.CourseView;
    
import Views.AdminView.*;
import Controllers.Controller;
import Models.Course;
import javax.swing.JOptionPane;

public class CourseEditInformationView extends javax.swing.JFrame {
    private Course course;
    /**
     * Creates new form AdminMenuView
     */
    public CourseEditInformationView() {
        initComponents();
        setLocationRelativeTo(this);
        setTitle("Edit Course");
    }

    public void setCourse(Course course) {
        this.course = course;
        courseNameLabelShow.setText(this.course.getCourseName());
        courseCreditsFieldEdit.setText(this.course.getCourseCredits()+"");
        courseMaxStudentsFieldEdit.setText(this.course.getMaxStudentsRegister()+"");
        courseLocationFieldEdit.setText(this.course.getCourseLocation());
    }

    public Course getCourse() {
        return course;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        courseNameLabelEdit = new javax.swing.JLabel();
        courseCreditsLabelEdit = new javax.swing.JLabel();
        courseMaxStudentsLabelEdit = new javax.swing.JLabel();
        courseLocationLabelEdit = new javax.swing.JLabel();
        courseLocationFieldEdit = new javax.swing.JTextField();
        courseCreditsFieldEdit = new javax.swing.JTextField();
        courseMaxStudentsFieldEdit = new javax.swing.JTextField();
        courseNameLabelShow = new javax.swing.JLabel();
        backEditCourseBtn = new javax.swing.JButton();
        doneEditCourseBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        courseNameLabelEdit.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        courseNameLabelEdit.setText("Course Name:");

        courseCreditsLabelEdit.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        courseCreditsLabelEdit.setText("Credits:");

        courseMaxStudentsLabelEdit.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        courseMaxStudentsLabelEdit.setText("Max Students:");

        courseLocationLabelEdit.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        courseLocationLabelEdit.setText("Location:");

        courseLocationFieldEdit.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        courseCreditsFieldEdit.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        courseMaxStudentsFieldEdit.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        courseNameLabelShow.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        courseNameLabelShow.setText("jLabel3");

        backEditCourseBtn.setText("Back");
        backEditCourseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backEditCourseBtnActionPerformed(evt);
            }
        });

        doneEditCourseBtn.setText("Done");
        doneEditCourseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doneEditCourseBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(courseNameLabelEdit)
                            .addComponent(courseCreditsLabelEdit)
                            .addComponent(courseMaxStudentsLabelEdit)
                            .addComponent(courseLocationLabelEdit))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(courseNameLabelShow)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(courseMaxStudentsFieldEdit)
                                .addComponent(courseLocationFieldEdit)
                                .addComponent(courseCreditsFieldEdit, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 601, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(281, 281, 281)
                        .addComponent(backEditCourseBtn)
                        .addGap(45, 45, 45)
                        .addComponent(doneEditCourseBtn)))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(courseNameLabelEdit)
                    .addComponent(courseNameLabelShow))
                .addGap(64, 64, 64)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(courseCreditsLabelEdit)
                    .addComponent(courseCreditsFieldEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(courseMaxStudentsFieldEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(courseMaxStudentsLabelEdit))
                .addGap(60, 60, 60)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(courseLocationLabelEdit)
                    .addComponent(courseLocationFieldEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backEditCourseBtn)
                    .addComponent(doneEditCourseBtn))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 11, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void doneEditCourseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doneEditCourseBtnActionPerformed
        // TODO add your handling code here:
        try{
        String courseCredits = courseCreditsFieldEdit.getText();
        String courseMaxStudent = courseMaxStudentsFieldEdit.getText();
        String courseLocation = courseLocationFieldEdit.getText();
        course.setCourseCredits(Integer.parseInt(courseCredits));
        course.setMaxStudentsRegister(Integer.parseInt(courseMaxStudent));
        course.setCourseLocation(courseLocation);
        this.dispose();
        Controller.courseEditController(course);}
        catch(NumberFormatException ex){
            JOptionPane.showMessageDialog(this, "Enter numbers only!");
            courseCreditsFieldEdit.setText("");
            courseMaxStudentsFieldEdit.setText("");
            courseCreditsFieldEdit.requestFocus();
        }
    }//GEN-LAST:event_doneEditCourseBtnActionPerformed

    private void backEditCourseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backEditCourseBtnActionPerformed
        this.dispose();
        new AdminManipulateCourseView().setVisible(true);
    }//GEN-LAST:event_backEditCourseBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CourseEditInformationView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CourseEditInformationView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CourseEditInformationView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CourseEditInformationView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               new CourseEditInformationView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backEditCourseBtn;
    private javax.swing.JTextField courseCreditsFieldEdit;
    private javax.swing.JLabel courseCreditsLabelEdit;
    private javax.swing.JTextField courseLocationFieldEdit;
    private javax.swing.JLabel courseLocationLabelEdit;
    private javax.swing.JTextField courseMaxStudentsFieldEdit;
    private javax.swing.JLabel courseMaxStudentsLabelEdit;
    private javax.swing.JLabel courseNameLabelEdit;
    private javax.swing.JLabel courseNameLabelShow;
    private javax.swing.JButton doneEditCourseBtn;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
