/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views.AdminView;

import Controllers.Controller;
import Controllers.ValidException;
import Models.User;
import Models.User_Model;
import javax.swing.JOptionPane;

/**
 *
 * @author Quan's PC
 */
public class AdminRegisterStudentView extends javax.swing.JFrame {

    private User student;

    /**
     * Creates new form AdminMenuView
     */
    public AdminRegisterStudentView() {
        initComponents();
        student = new User();
        student.setUserId(User_Model.getNewUserId());
        student.setUserRole("student");
        studentIdFieldRegister.setText(student.getUserId() + "");
        studentIdFieldRegister.setEnabled(false);
        setLocationRelativeTo(this);
        setTitle("Student's Registration");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        usernameLabelRegister = new javax.swing.JLabel();
        passwordLabelRegister = new javax.swing.JLabel();
        phoneLabelRegister = new javax.swing.JLabel();
        emailLabelRegister = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        doneFacultyAdminBtn = new javax.swing.JButton();
        backFacultyAdminBtn = new javax.swing.JButton();
        usernameFieldRegister = new javax.swing.JTextField();
        emailFieldRegister = new javax.swing.JTextField();
        phoneFieldRegister = new javax.swing.JTextField();
        facultyIdLabelRegister = new javax.swing.JLabel();
        studentIdFieldRegister = new javax.swing.JTextField();
        firsetNameLabelRegister = new javax.swing.JLabel();
        firstNameFieldRegister = new javax.swing.JTextField();
        midNameLabelRegister = new javax.swing.JLabel();
        midNameFieldRegister = new javax.swing.JTextField();
        lastNameLabelRegister = new javax.swing.JLabel();
        lastNameFieldRegister = new javax.swing.JTextField();
        passwordFieldRegister = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        confirm = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        usernameLabelRegister.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        usernameLabelRegister.setText("Username:");

        passwordLabelRegister.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        passwordLabelRegister.setText("Password:");

        phoneLabelRegister.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        phoneLabelRegister.setText("Phone:");

        emailLabelRegister.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        emailLabelRegister.setText("Email:");

        doneFacultyAdminBtn.setText("Done");
        doneFacultyAdminBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doneFacultyAdminBtnActionPerformed(evt);
            }
        });

        backFacultyAdminBtn.setText("Back");
        backFacultyAdminBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backFacultyAdminBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(354, 354, 354)
                .addComponent(backFacultyAdminBtn)
                .addGap(41, 41, 41)
                .addComponent(doneFacultyAdminBtn)
                .addContainerGap(325, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backFacultyAdminBtn)
                    .addComponent(doneFacultyAdminBtn))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        usernameFieldRegister.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        emailFieldRegister.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        phoneFieldRegister.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        facultyIdLabelRegister.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        facultyIdLabelRegister.setText("StudentID:");

        studentIdFieldRegister.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        firsetNameLabelRegister.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        firsetNameLabelRegister.setText("FirstName:");

        firstNameFieldRegister.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        midNameLabelRegister.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        midNameLabelRegister.setText("MidName:");

        midNameFieldRegister.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        lastNameLabelRegister.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lastNameLabelRegister.setText("LastName:");

        lastNameFieldRegister.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        passwordFieldRegister.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Confirm password:");

        confirm.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(facultyIdLabelRegister)
                                .addComponent(firsetNameLabelRegister))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGap(102, 102, 102)
                                    .addComponent(studentIdFieldRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 649, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(lastNameLabelRegister)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(lastNameFieldRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addComponent(passwordLabelRegister)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(phoneLabelRegister)
                                        .addGap(101, 101, 101))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(usernameLabelRegister)
                                        .addGap(72, 72, 72))
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING))
                                .addComponent(emailLabelRegister))
                            .addGap(32, 32, 32)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(usernameFieldRegister)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(firstNameFieldRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(33, 33, 33)
                                    .addComponent(midNameLabelRegister)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(midNameFieldRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(passwordFieldRegister)
                                .addComponent(confirm, javax.swing.GroupLayout.DEFAULT_SIZE, 649, Short.MAX_VALUE)
                                .addComponent(phoneFieldRegister)
                                .addComponent(emailFieldRegister)))))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(studentIdFieldRegister, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(facultyIdLabelRegister))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstNameFieldRegister, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(midNameLabelRegister)
                    .addComponent(midNameFieldRegister, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lastNameLabelRegister)
                    .addComponent(lastNameFieldRegister, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(firsetNameLabelRegister))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usernameFieldRegister, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(usernameLabelRegister))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordFieldRegister, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passwordLabelRegister))
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(confirm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(phoneLabelRegister)
                    .addComponent(phoneFieldRegister, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailLabelRegister)
                    .addComponent(emailFieldRegister, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void doneFacultyAdminBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doneFacultyAdminBtnActionPerformed
        // TODO add your handling code here:

        // TODO add your handling code here:
        try {
            String firstName = firstNameFieldRegister.getText();
            String midName = midNameFieldRegister.getText();
            String lastName = lastNameFieldRegister.getText();
            String userName = usernameFieldRegister.getText();
            String newPassword = String.valueOf(passwordFieldRegister.getPassword());
            String confirmPassword = String.valueOf(confirm.getPassword());
            if (!newPassword.equals(confirmPassword)) {
                JOptionPane.showMessageDialog(this, "Password and confirm password do not match. Please re-enter.");
                return;
            }
            String phone = phoneFieldRegister.getText();
            if(!phone.matches("\\d+")){
                throw new ValidException("Enter phone number");
            }
            String emaail = emailFieldRegister.getText();
            student.setFirstName(firstName.trim());
            student.setMidName(midName.trim());
            student.setLastName(lastName.trim());
            student.setUsername(userName.trim());
            student.setPassword(newPassword.trim());
            student.setPhone(phone.trim());
            student.setEmail(emaail.trim());
            Controller.userRegisterStudentController(student, this);
        } catch (ValidException ex) {
            JOptionPane.showMessageDialog(this, ex);
            phoneFieldRegister.setText("");
            phoneFieldRegister.requestFocus();
        }
    }//GEN-LAST:event_doneFacultyAdminBtnActionPerformed

    private void backFacultyAdminBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backFacultyAdminBtnActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new AdminMenuView().setVisible(true);
    }//GEN-LAST:event_backFacultyAdminBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminRegisterStudentView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminRegisterStudentView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminRegisterStudentView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminRegisterStudentView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminRegisterStudentView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backFacultyAdminBtn;
    private javax.swing.JPasswordField confirm;
    private javax.swing.JButton doneFacultyAdminBtn;
    private javax.swing.JTextField emailFieldRegister;
    private javax.swing.JLabel emailLabelRegister;
    private javax.swing.JLabel facultyIdLabelRegister;
    private javax.swing.JLabel firsetNameLabelRegister;
    private javax.swing.JTextField firstNameFieldRegister;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField lastNameFieldRegister;
    private javax.swing.JLabel lastNameLabelRegister;
    private javax.swing.JTextField midNameFieldRegister;
    private javax.swing.JLabel midNameLabelRegister;
    private javax.swing.JPasswordField passwordFieldRegister;
    private javax.swing.JLabel passwordLabelRegister;
    private javax.swing.JTextField phoneFieldRegister;
    private javax.swing.JLabel phoneLabelRegister;
    private javax.swing.JTextField studentIdFieldRegister;
    private javax.swing.JTextField usernameFieldRegister;
    private javax.swing.JLabel usernameLabelRegister;
    // End of variables declaration//GEN-END:variables
}
